addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.4")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"       % "0.13.1")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"            % "2.7.1")
addSbtPlugin("com.eed3si9n"   % "sbt-unidoc"          % "0.4.3")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"      % "1.9.3")
addSbtPlugin("com.eed3si9n"   % "sbt-assembly"        % "0.14.6")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.1")
addSbtPlugin("dev.zio"        % "zio-sbt-website"     % "0.3.9")

resolvers += Resolver.sonatypeRepo("public")
