addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.6")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"            % "2.8.2")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"      % "1.12.1")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"          % "0.6.1")
addSbtPlugin("com.eed3si9n"   % "sbt-assembly"        % "2.5.0")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"       % "0.13.1")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.7")
addSbtPlugin("dev.zio"        % "zio-sbt-website"     % "0.8.6")
addSbtPlugin("dev.zio"        % "zio-sbt-ci"          % "0.8.6")

resolvers += Resolver.sonatypeRepo("public")
